### ISSUE TITLE
[API Suggestion] Doors & Sabotages

### ISSUE THREAD

**Issue by AlexejheroYTB** [Impostor/Impostor#133]
## Api suggestion & missing data

- [ ] Doors
  - [x] Trigger event on door close (#132)
  - [ ] Skeld
    - [ ] Trigger event on door open
    - [ ] Trigger door close from API
    - [ ] Trigger door open from API (is this possible?)
  - [ ] Polus
    - [x] Trigger event on door open (#132)
    - [ ] Trigger door close from API
    - [ ] Trigger door open from API
- [ ] Decontamination Doors
  - [x] Trigger event on manual door open (#132)
  - [ ] Trigger event on automatic door close
  - [ ] Trigger event on automatic door open
- [ ] Sabotages
  - [x] Trigger events on sabotage (#132)
  - [ ] Trigger events on sabotage fix
  - [x] Trigger sabotages from API (#132)
    - [ ] Figure out a way to bypass the sabotage cooldown
  - [ ] Reactor / Seismic
    - [ ] See which of the two buttons are pressed and who is pressing them
    - [ ] Hold one of the reactor buttons from server-side
    - [ ] Repair sabotage
  - [ ] Oxygen
    - [ ] See which of the two oxygens have been fixed and by whom
    - [ ] Fix one of the oxygens server-side
    - [ ] Repair sabotage
  - [ ] Lights
    - [ ] See which light switches are on and which are off and who is toggling them
    - [ ] Flip switches from API
    - [ ] Repair sabotage
  - [ ] Comms
    - [ ] Skeld & Polus
      - [ ] Repair sabotage
    - [ ] Mira HQ
      - [ ] See which of the two comms have been fixed and by whom
      - [ ] Fix one of the comms server-side
      - [ ] Repair sabotage

---

### Use case

Trigger sabotages, keep lights off, fix reactor/miracomms solo, etc.
