### ISSUE TITLE
Handle messages sent by host

### ISSUE THREAD

**Issue by Hiumee** [Impostor/Impostor#252]
# Description

The messages sent by host (using `GameDataTag.DataFlag`) are used to broadcast changes to the players.

Use case: This can be used to detect, start and stop sabotages.

### TODO - Ship events

- [x] Doors
  - [ ] Trigger event on state changed
  - [ ] Open/Close doors from API
- [x] Communication
  - [x] Trigger event on state changed
  - [x] Start/Stop sabotage from API
- [x] Oxygen
  - [x] Trigger event on state changed
  - [x] Start/Stop sabotage from API
- [ ] Medbay Scan
  - [ ] Trigger event on state changed (player using scan, waiting for scan)
- [x] Reactor
  - [x] Trigger event on state changed (turning on/off, players holding/releasing buttons)
  - [x] Start/Stop sabotage from API
- [x] Sabotage cooldown
  - [x] Set the impostor's sabotage cooldown from API
- [ ] Security cameras (cameras blinking)
  - [ ] Maybe: Hide/Show cameras blinking from API
- [x] Electrical
  - [x] Trigger event on state changed (start/stop sabotage, switch flipped)
  - [x] Start/Stop sabotage from API
  - [x] Maybe: Change switch state from API
